repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    -   id: black
- repo: https://github.com/Checkmarx/kics
  rev: v1.6.0
  hooks:
      - id: kics-scan
        verbose: true
        args: [--ignore-on-exit, "all"]
